project:
  type: website
  # post-render: 
  #   - code/webshot_img.R

website:
  title: "2024-Presentations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

